---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# dataplotr

This package mainly contains wrapper functions for ggplot2.


## Installation

You can install dataplotr from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("aotearoastats/dataplotr")
```

## plot_barplot
Plot_barplot plots simple barplots with the option to add a grid. See `?plot_barplot` for documentation.


```{r plot_barplot_exampe, message=FALSE, warning=FALSE}
library(dataplotr)
library(dplyr)
iris.plot <- iris %>% 
  group_by(Species) %>% 
  summarize(Sepal.Length=mean(Sepal.Length))

plot_barplot(iris.plot,
             main_title="Sepal.Length by Species on the Iris Data Set",
             x_var = "Species",
             y_var = "Sepal.Length",
             fill_title = "Species",
             fill_vars = "Species",
             colour_vars = "rev(Species)")

```
